#!/usr/bin/env python3

import math

import rclpy
import rclpy.node
import std_msgs.msg


class TestNode(rclpy.node.Node):
    def __init__(self):
        super().__init__("radian")
        self.pub_double = self.create_publisher(std_msgs.msg.Float64, "/test/radian", 1)
        self.count = 0
        self.timer = self.create_timer(0.1, self.on_timer)

    def on_timer(self):
        msg = std_msgs.msg.Float64()
        msg.data = 2.0 * math.pi * self.count * 0.01
        self.pub_double.publish(msg)
        self.count = (self.count + 1) % 100


def main(args=None):
    rclpy.init(args=args)
    node = TestNode()
    rclpy.spin(node)
    rclpy.shutdown()


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        pass
