# --------------------------------------------------
# headers
# --------------------------------------------------
version: alpha 1
root: main

# --------------------------------------------------
# defaults
# --------------------------------------------------
defaults:

  - class: simple
    style: {font-size: 12}

  - class: titled
    style:
      title: {font-size: 12}
      value: {font-size: 24}

# --------------------------------------------------
# monitors
# --------------------------------------------------
monitors:

  main:
    class: matrix
    cols: 3
    rows: 2
    children:
      - data_name_1
      - data_name_2
      - data_name_3
      - data_name_4
      - data_name_5
      - data_name_6

  data_name_1:
    class: titled
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: stamp.sec}
    title: Second

  data_name_2:
    class: titled
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: stamp.nanosec}
    title: Nanosecond
    style:
      title: {font-size: 12}
      value: {font-size: 24}

  data_name_3:
    class: titled
    topic: {name: /monitor/float, type: std_msgs/msg/Float32}
    field: {name: data}
    title: Float Value
    rules:
      - {func: units, args: mps_to_kph}
      - {func: precision, args: 2}

  data_name_4:
    class: simple
    topic: {name: /monitor/header, type: std_msgs/msg/Header}
    field: {name: frame_id}
    style: {font-size: 24}
    rules:
      - {func: lines, args: 2}

  data_name_5:
    class: simple
    topic: {name: /monitor/int, type: std_msgs/msg/Int32}
    field: {name: data}
    title: "Value: "
    rules:
      - func: switch
        default: {value: ERROR}
        mapping:
          1: {value: A, style: {back-color: "#FF00FF"}}
          2: {value: B, style: {back-color: "#00FF00"}}
          3: {value: C, style: {back-color: "#00FFFF"}}

  data_name_6:
    class: simple
    topic: {name: /monitor/array, type: std_msgs/msg/Int32MultiArray, qos: {durability: transient_local}}
    field: {name: data@0}
