# --------------------------------------------------
# metadata
# --------------------------------------------------
version: 1
root: layout_main

# --------------------------------------------------
# defaults
# --------------------------------------------------
defaults: ~

# --------------------------------------------------
# widgets
# --------------------------------------------------
widgets:
  layout_main:
    class: layout::multi_data_monitor::Matrix
    param: { cols: 3, rows: 2 }
    children:
      - widget1
      - widget2
      - class: layout::multi_data_monitor::Matrix
        param: { cols: 1, rows: 1 }
        children:
          - class: widget::multi_data_monitor::Title
            param: { title: Second }
            input:
              class: filter
              input: { class: topic, name: /test/header, data: frame_id, type: std_msgs/msg/Header, qos: RT2 }

  widget1:
    class: widget::multi_data_monitor::Title
    param: { title: Second }
    input: { class: topic, name: /test/header, data: stamp.sec, type: std_msgs/msg/Header, qos: RT2 }

  widget2:
    class: widget::multi_data_monitor::Title
    param: { title: Nanosecond }
    input:
      class: filter
      input: { class: topic, name: /test/header, data: stamp.nanosec }
      rules:
        - { class: aaa }
        - { class: bbb }
        - { class: ccc }

# --------------------------------------------------
# streams
# --------------------------------------------------:
streams:
  stream1:
    class: filter
    input: stream2
    rules:
      - { class: aaa }
      - { class: bbb }

  stream2:
    class: filter
    input: { class: topic, name: /test/double, data: data, type: std_msgs/msg/Float64 }
    rules:
      - { class: aaa }
      - { class: bbb }

  stream3: { class: topic, name: /test/uint32, data: data, type: std_msgs/msg/Uint32 }
