# --------------------------------------------------
# metadata
# --------------------------------------------------
version: 1

# --------------------------------------------------
# style
# --------------------------------------------------
stylesheets:
  - { path: /home/isamu-takagi/working/multi_data_monitor/multi_data_monitor/config/css/default.css }
  - { path: /home/isamu-takagi/working/multi_data_monitor/multi_data_monitor/config/css/colors.css }
  - { package: multi_data_monitor, path: config/css/plugins/simple.css, target: multi_data_monitor::Simple }

# --------------------------------------------------
# widgets
# --------------------------------------------------
widgets:
  root:
    class: multi_data_monitor::Matrix
    param: { cols: 3, rows: 2 }
    children:
      - widget1
      - widget2
      - widget3

  widget1:
    class: multi_data_monitor::Simple
    param: { title: Frame }
    input: { class: topic, name: /test/header, data: frame_id, type: std_msgs/msg/Header }

  widget2:
    class: multi_data_monitor::Simple
    param: { title: Second }
    input: { class: topic, name: /test/header, data: stamp.sec, type: std_msgs/msg/Header }

  widget3:
    class: multi_data_monitor::Simple
    param: { title: NanoSecond }
    input:
      class: filter
      input: { class: topic, name: /test/header, data: stamp.nanosec, type: std_msgs/msg/Header }
      rules:
        - { class: multi_data_monitor::TestFilter }
