# --------------------------------------------------
# headers
# --------------------------------------------------
version: 0
root: main

# --------------------------------------------------
# defaults
# --------------------------------------------------
defaults: ~

# --------------------------------------------------
# monitors
# --------------------------------------------------
monitors: ~
