# --------------------------------------------------
# metadata
# --------------------------------------------------
version: 1

# --------------------------------------------------
# defaults
# --------------------------------------------------
defaults: ~

# --------------------------------------------------
# widgets
# --------------------------------------------------
widgets:
  root: main
  main: hoge
  hoge: fuga
  fuga:
    class: multi_data_monitor::Matrix
    param: { cols: 3, rows: 2 }
    children:
      - widget1
      - widget2
      - class: multi_data_monitor::Matrix
        param: { cols: 1, rows: 1 }
        children:
          - class: multi_data_monitor::Simple
            param: { title: Second }
            input:
              class: filter
              input: { class: topic, name: /test/header, data: frame_id, type: std_msgs/msg/Header, qos: RV1 }

  widget1:
    class: multi_data_monitor::Simple
    param: { title: Second }
    input: { class: topic, name: /test/header, data: stamp.sec, type: std_msgs/msg/Header, qos: RV1 }

  widget2:
    class: multi_data_monitor::Simple
    param: { title: Nanosecond }
    input:
      class: filter
      input: { class: topic, name: /test/header, data: stamp.nanosec }
      rules:
        - { class: aaa }
        - { class: bbb }
        - { class: ccc }

  widget3:
    class: multi_data_monitor::Simple
    input: stream3

  widget4:
    class: multi_data_monitor::Simple
    input: stream7

# --------------------------------------------------
# streams
# --------------------------------------------------:
streams:
  stream1:
    class: filter
    input: stream2
    rules:
      - { class: aaa }
      - { class: bbb }

  stream2:
    class: filter
    input: { class: topic, name: /test/double, data: data, type: std_msgs/msg/Float64 }
    rules:
      - { class: aaa }
      - { class: bbb }

  stream5: stream6
  stream6: stream7
  stream3: stream4
  stream4: stream5
  stream7: { class: topic, name: /test/uint32, data: data, type: std_msgs/msg/UInt32 }
