# --------------------------------------------------
# metadata
# --------------------------------------------------
version: 0
root: layout_main

# --------------------------------------------------
# defaults
# --------------------------------------------------
defaults: ~

# --------------------------------------------------
# monitors
# --------------------------------------------------
monitors:
  layout_main:
    class: multi_data_monitor::Matrix
    param: { cols: 3, rows: 2 }
    children:
      - widget1
      - widget2
      - class: multi_data_monitor::Matrix
        param: { cols: 1, rows: 1 }
        children:
          - class: multi_data_monitor::Title
            param: { title: Second }
            input:
              class: filter
              input: { class: topic, name: /test/header, data: frame_id, type: std_msgs/msg/Header }

  widget1:
    class: multi_data_monitor::Title
    param: { title: Second }
    input: { class: topic, name: /test/header, data: stamp.sec, type: std_msgs/msg/Header }

  widget2:
    class: multi_data_monitor::Title
    param: { title: Nanosecond }
    input:
      class: filter
      input: { class: topic, name: /test/header, data: stamp.nanosec, type: std_msgs/msg/Header }
      rules:
        - aaa
        - bbb
        - ccc

# --------------------------------------------------
# messages
# --------------------------------------------------:
messages:
  stream1:
    class: filter
    input: stream2
    rules:
      - aaa
      - bbb

  stream2:
    class: filter
    input: { class: topic, name: /test/double, data: data, type: std_msgs/msg/Float64 }
    rules:
      - aaa
      - bbb

  stream3: { class: topic, name: /test/uint32, data: data, type: std_msgs/msg/Uint32 }
