# --------------------------------------------------
# metadata
# --------------------------------------------------
version: 1

# --------------------------------------------------
# style
# --------------------------------------------------
stylesheets:
  - { path: file:///home/isamu-takagi/working/multi_data_monitor/multi_data_monitor/config/css/default.css }
  - { path: file:///home/isamu-takagi/working/multi_data_monitor/multi_data_monitor/config/css/colors.css }
  - { path: package://multi_data_monitor/config/css/plugins/simple.css, target: multi_data_monitor::Simple }
  - { path: package://multi_data_monitor/config/css/plugins/title.css, target: multi_data_monitor::Title }

# --------------------------------------------------
# widgets
# --------------------------------------------------
widgets:
  root:
    class: multi_data_monitor::Matrix
    cols: 3
    rows: 2
    children:
      - widget1
      - widget2
      - widget3
      - { class: multi_data_monitor::Simple }
      - { class: multi_data_monitor::Simple }
      - { class: multi_data_monitor::Simple }

  widget1:
    class: multi_data_monitor::Title
    title: "Text: "
    notes: The description displayed when mouse over
    input:
      class: filter
      input: { class: topic, name: /test/uint32, data: data, type: std_msgs/msg/UInt32 }
      rules:
        - class: multi_data_monitor::Switch
          default: { value: ERROR, attrs: { background-color: "" } }
          mapping:
            1: { value: A, attrs: { background-color: green } }
            2: { value: B, attrs: { background-color: yellow } }
            3: { value: C, attrs: { background-color: red } }

  widget2:
    class: multi_data_monitor::Title
    param: { title: Second }
    input: { class: topic, name: /test/header, data: stamp.sec, type: std_msgs/msg/Header }

  widget3:
    class: multi_data_monitor::Title
    param: { title: NanoSecond }
    input:
      class: filter
      input: { class: topic, name: /test/header, data: stamp.nanosec, type: std_msgs/msg/Header }
      rules:
        - { class: multi_data_monitor::Format, type: double, format: "{:.3f}" }
